	set clipboard=unnamedplus
	syntax enable
	set number
	set encoding=UTF-8
	set tabstop=4
	set softtabstop=4
	set shiftwidth=4
	set autoindent
	set mouse=a
	set termguicolors
	set background=dark
	colorscheme catppuccin
